export const dataUnidades = [
  {
    id: "1",
    title: "PSF I",
    bairro: "Matadouro",
    rua: "Fulana de Tal n° 1587",
    medicos: [
      {
        id: "1",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "2",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "3",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
      {
        id: "4",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "5",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "6",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
    ],
  },
  {
    id: "2",
    title: "PSF II",
    bairro: "Bela Vista",
    rua: "Fulana de Tal n° 1587",
    medicos: [
      {
        id: "1",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "2",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "3",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
      {
        id: "4",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "5",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "6",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
    ],
  },
  {
    id: "3",
    title: "PSF III",
    bairro: "Centro",
    rua: "Fulana de Tal n° 1587",
    medicos: [
      {
        id: "1",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "2",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "3",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
      {
        id: "4",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "5",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "6",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
    ],
  },
  {
    id: "4",
    title: "PSF IV",
    bairro: "Lagoa do Mato",
    rua: "Fulana de Tal n° 1587",
    medicos: [
      {
        id: "1",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "2",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "3",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
      {
        id: "4",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "5",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "6",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
    ],
  },
  {
    id: "5",
    title: "PSF V",
    bairro: "Padre Cícero",
    rua: "Fulana de Tal n° 1587",
    medicos: [
      {
        id: "1",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "2",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "3",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
      {
        id: "4",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "5",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "6",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
    ],
  },
  {
    id: "6",
    title: "PSF VI",
    bairro: "São Judas",
    rua: "Fulana de Tal n° 1587",
    medicos: [
      {
        id: "1",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "2",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "3",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
      {
        id: "4",
        title: "Leonardo Santos",
        espcialidade: "clinico geral",
        crm: "15874958756",
      },
      {
        id: "5",
        title: "Emmily Tainara",
        espcialidade: "pediatra",
        crm: "5784968713",
      },
      {
        id: "6",
        title: "Adriano Silva",
        espcialidade: "ortopedista",
        crm: "31468764156",
      },
    ],
  },
];
